### ISSUE TITLE
in log4j-input, the "path" is not correct

### ISSUE THREAD

**Issue by OhadR** [logstash-plugins/logstash-input-log4j#12]
i use 
input {  log4j {} }
and: 
output { stdout { codec => rubydebug } }

when my app prints something to the log, i see:
{
        "message" => "<the message>",
       "@version" => "1",
     "@timestamp" => "2015-06-05T20:28:23.312Z",
           "type" => "log4j",
           "host" => "127.0.0.1:52083",
           "path" => "com.ohadr.logs_provider.MyServlet",
       "priority" => "INFO",
    "logger_name" => "com.ohadr.logs_provider.MyServlet",
         "thread" => "http-apr-8080-exec-3",
          "class" => "?",
           "file" => "?:?",
         "method" => "?",
}
the issue is that the **"path"** field is wrong; AFAI understand, it should be the _path of the file_. instead, I get the same value as "logger_name". I need "path" to be the path-of-file, including the file-name, so this way i can distinguish between logs from different files.
How can it be fixed?

thanks!

in log4j.rb (https://github.com/logstash-plugins/logstash-input-log4j/blob/master/lib/logstash/inputs/log4j.rb):
event["path"] = log4j_obj.getLoggerName

**Comment by wwsean08** [comment]
Based on the code that is what you should get:
`event["path"] = log4j_obj.getLoggerName`
 I'll look into log4j and see if it's possible to get the path over the weekend or next week and if it's possible will try and fix it.

**Comment by wwsean08** [comment]
After some testing, log4j doesn't provide the path to the file (not too surprising given the way that java works and the fact that the actual path would be a jar file).  However it does provide the location information filled out in class, file, and method (though you are getting the "Not Available" variable back which means it's not sending or not included for some reason.  I am getting this information on my system because I set it enabled, here is the property you need to set:

log4j.appender.{APPENDER}.LocationInfo=true

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice
