### ISSUE TITLE
Support Log4j v2

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-input-log4j#33]
Although adoption for Log4j v2 has been slow, it appears to be emerging more and more.

Support for v2 of the protocol would be useful.

**Comment by CraigFoote** [comment]
+1
We have a client entrenched in Log4J v.2 and it would require lots of code changes to downgrade (https://logging.apache.org/log4j/2.x/manual/migration.html) and they expect better performance from v.2. We could work with the client if the log4j logstash input plugin supported v.2, presumably through a 'version2' boolean option or the like.

**Comment by joergsesterhenn** [comment]
+1

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice

**Comment by jordansissel** [comment]
News! No implementation is necessary, luckily! The log4j folks informed me that Socket appenders can use different layouts. The following allows you to send line-delimited JSON logs over a socket using log4j:

The following only works in log4j2.

log4j2.xml:

```
<Configuration status="WARN">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="[%d{ISO8601}][%-5p][%-25c] %m%n" />
    </Console>
    <Socket name="Socket" host="localhost" port="12345">
      <JsonLayout compact="true" eventEol="true" />
    </Socket>
  </Appenders>
  <Loggers>
    <Root level="info">
      <AppenderRef ref="Console"/>
      <AppenderRef ref="Socket"/>
    </Root>
  </Loggers>
</Configuration>
```

You can receive this in Logstash by doing the following input:

```
input {
  tcp {
    port => 12345
    codec => json_lines
  }
}
```

Still, because TCP logging is lossy and could block your application, if either loss or blocking are things you want to avoid, it is strongly recommended that you write to local files and ship the logs with filebeat.
