### ISSUE TITLE
problems bootstrapping in a linux environment

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-input-log4j#5]
Hi,
 there might be an issue while fetching the dependencies for this plugin and a linux environment. Actually in jenkins the test build is failing with this error:

```
Using rspec-mocks 2.14.6
Using rspec 2.14.1
Using logstash-devutils 0.0.10
[ERROR] Failed to execute goal on project logstash-input-log4j: Could not resolve dependencies for project rubygems:logstash-input-log4j:gem:0.1.3: Failed to collect dependencies at rubygems:logstash-core:gem:[1.4.0,2.0.0): No versions available for rubygems:logstash-core:gem:[1.4.0,2.0.0) within specified range -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Errno::ENOENT: No such file or directory - /home/jenkins/workspace/logstash_input_log4j_commit/logstash-input-log4j/deps.lst
An error occurred while installing logstash-input-log4j (0.1.3), and Bundler
cannot continue.
Make sure that `gem install logstash-input-log4j -v '0.1.3'` succeeds before
bundling.
F

Failures:

  1) inputs/log4j should register
     Failure/Error: input = LogStash::Plugin.lookup("input", "log4j").new("mode" => "client")
     LogStash::PluginLoadingError:
       Couldn't find any input plugin named 'log4j'. Are you sure this is correct? Trying to load the log4j input plugin resulted in this error: no such file to load -- logstash-input-log4j_jars
     # ./spec/inputs/log4j_spec.rb:8:in `(root)'

Finished in 0.074 seconds
1 example, 1 failure
```

**Comment by wiibaa** [comment]
same error on my windows env

**Comment by wiibaa** [comment]
I got the same error trying to `bundle install` a fresh clone of **logstash-output-elasticsearch**
So it seems that any logstash plugin with direct jar dependencies are experiencing issue, kafka is a different topic because the jar are not required directly but are part of jruby-kafka gem...
Very puzzling

**Comment by wiibaa** [comment]
I got on step further by using specific logstash-core gem version in the gemspec 
````
s.add_runtime_dependency "logstash-core", '1.5.0.rc2'
````
I strongly suspect that ruby-maven is having a hard time because logstash-core gem versioning does not follow [maven convention for qualifier](http://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401)
So for him, none of the [available version in rubygem ](https://rubygems.org/gems/logstash-core) are following the rule [1.4.0,2.0.0)

This should be fixed with 1.5.0 release hopefully

**Comment by purbon** [comment]
@wiibaa Interesting issue, I guess we aim to make both happy at the end, but now sure which is the best way to archive it. 

I took a look at the way rubygems seems to expect versions (http://guides.rubygems.org/specification-reference/#version) and looks like he expect the nottion we're using in here.

**Comment by purbon** [comment]
@wiibaa speaking about the bootstrapping problem, If I'm not mistaken this got fix throw https://github.com/elastic/logstash/pull/2596, do you mind closing we close this issue and move your version naming issue to the main logstash repo?

**Comment by wiibaa** [comment]
@purbon sure please do!

**Comment by purbon** [comment]
ok! moving the naming issue to the main logstash repo and closing this as I think is already solved. If not, we can reopen this issue.
